#!/bin/bash
# Made by Pserg
# Version: 1.1

if [ $# -lt 1 ]; then
    echo usage:  error.
    exit 1
fi

domain=$1

PATH=$PATH:/usr/local/vesta/bin
export PATH

user=$(/usr/local/vesta/bin/v-search-domain-owner $domain)

# email="info@$domain";
if [ $# -gt 1 ]; then
    newdomain=$2
fi
if [ -z "$user" ]
then
echo ""
      echo "\$user is empty $3"
	  echo ""
	  user=$3
else
echo ""
      echo "\$user is NOT empty"
	  echo ""
fi
if [ ! -d "/home/$user" ]; then
    echo "User doesn't exist";
    exit 1;
fi

/usr/local/vesta/bin/v-add-domain $user $newdomain
# if [ ! -d "/home/$user/web/$domain/public_html" ]; then
# /usr/local/vesta/bin/v-add-domain $user $domain
#     #echo "Domain doesn't exist";
#     #exit 1;
# 	user=$(/usr/local/vesta/bin/v-search-domain-owner $domain)
# # 	if [ ! -d "/home/$user/web/$domain/public_html" ]; then
# # 
# #     echo "OLd domain doesn't exist";
# #     exit 1;
# # 	
# # fi
# fi
#cd "/home/$user/web/$domain/public_html"
#wget http://wordpress.org/latest.tar.gz
#tar xfvz latest.tar.gz
#echo ""
#echo "done."
#exit 1;
# if [ ! -f "/home/$user/conf/web/ssl.$domain.pem" ]; then
#     v-add-letsencrypt-domain "$user" "$domain" "" "yes"
# 
#     if [ -f "/usr/local/vesta/data/templates/web/nginx/force-https.stpl" ]; then
#         v-change-web-domain-proxy-tpl  "$user" "$domain" "force-https" "jpeg,jpg,png,gif,bmp,ico,svg,tif,tiff,css,js,htm,html,ttf,otf,webp,woff,txt,csv,rtf,doc,docx,xls,xlsx,ppt,pptx,odf,odp,ods,odt,pdf,psd,ai,eot,eps,ps,zip,tar,tgz,gz,rar,bz2,7z,aac,m4a,mp3,mp4,ogg,wav,wma,3gp,avi,flv,m4v,mkv,mov,mpeg,mpg,wmv,exe,iso,dmg,swf" "no"
#     fi
# fi

WORKINGDIR="/home/$user/web/$newdomain/public_shtml"
# FILE=latest.tar.gz

rm -rf $WORKINGDIR/*

cp -r /home/$user/web/$domain/public_html/. /home/$user/web/$newdomain/public_shtml
echo "~~~~================================================================="
echo " Moved files to temp directory /home/$user/web/$newdomain/public_shtml" 

wpdbname=$(cat /home/$user/web/$newdomain/public_shtml/wp-config.php | grep DB_NAME | cut -d \' -f 4)
wpdbuser=$(cat /home/$user/web/$newdomain/public_shtml/wp-config.php | grep DB_USER | cut -d \' -f 4)
wpdbpass=$(cat /home/$user/web/$newdomain/public_shtml/wp-config.php | grep DB_PASSWORD | cut -d \' -f 4)

echo ""
echo "DB_NAME: $wpdbname"
echo ""
echo "DB_USER: $wpdbuser"
echo ""
echo "DB_PASSWORD: $wpdbpass"
echo ""

mysqldump -u $wpdbuser -p$wpdbpass $wpdbname  > /home/$user/web/$newdomain/public_shtml/dump.sql
sed -i   "s/$domain/$newdomain/g" /home/$user/web/$newdomain/public_shtml/dump.sql
uniq=$(cat /proc/sys/kernel/random/uuid | cut -c1-3)
newdbname=datbas$uniq
newdbuser=datbas$uniq
newpass=$(cat /proc/sys/kernel/random/uuid | cut -c1-16)

v-add-database $user $newdbname $newdbuser $newpass

echo "Created new database"
echo ""
echo "NEW DB_NAME: admin_$newdbname"
echo ""
echo "NEW DB_USER: admin_$newdbuser"
echo ""
echo "NEW DB_PASSWORD: $newpass"
echo ""

mysql -u admin_$newdbuser -p$newpass admin_$newdbname < /home/$user/web/$newdomain/public_shtml/dump.sql

echo "Updated new database"
echo ""

sed -i   "s/$domain/$newdomain/g" /home/$user/web/$newdomain/public_shtml/wp-config.php
sed -i   "s/$wpdbname/admin_$newdbname/g" /home/$user/web/$newdomain/public_shtml/wp-config.php
sed -i   "s/$wpdbuser/admin_$newdbuser/g" /home/$user/web/$newdomain/public_shtml/wp-config.php
sed -i   "s/$wpdbpass/$newpass/g" /home/$user/web/$newdomain/public_shtml/wp-config.php
sed -i   "s/$domain/$newdomain/g" /home/$user/web/$newdomain/public_shtml/robots.txt

echo "Changed wp-config.php and robots.txt"
echo ""

find /home/$user/web/$newdomain/public_html/ -name 'yandex*html'  -delete
rm /home/$user/web/$newdomain/public_shtml/dump.sql

echo "Deleted yandex file and dump"
echo ""

cp -r /home/$user/web/$newdomain/public_shtml/. /home/$user/web/$newdomain/public_html

echo "Moved files to /home/$user/web/$newdomain/public_html"
echo ""

rm -rf /home/$user/web/$newdomain/public_shtml/*

echo "Deleted temp files from /home/$user/web/$newdomain/public_shtml"
echo "" 

CONFIGDIR="/home/$user/conf/web/"
TEMPCONFIG=$CONFIGDIR"tempconf.txt"
OLDCONFIG=$CONFIGDIR$domain".nginx.conf"

sed -i "/location \/ {/{N;a \        if \(\$http_user_agent \~\* \"Googlebot\|Googlebot-Video\|APIs-Google\|AdsBot-Google-Mobile\|AdsBot-Google\|Googlebot-Image\|Googlebot-News\|AdsBot-Google-Mobile-Apps\"\) \{ \n           rewrite \^\/\(.*\)\$ http:\/\/$newdomain/\$1 permanent; \n        \} \n        if \(\$http_user_agent \~\* \"YandexBot\|YandexDirect\|YandexImages\|YandexMetrika\|YandexMobileBot\|YandexMedia\|YandexNews\|YandexPagechecker\|YandexMarket\|YandexCalenda\|YandexDirectDyn\|YaDirectFetcher\|YandexAccessibilityBot\|YandexScreenshotBot\|YandexVideoParser\|YandexSearchShop\|YandexOntoDBAPI\"\) \{ \n           rewrite \^\/\(.*\)\$ http:\/\/$newdomain/\$1 permanent; \n        \} \n
}" $OLDCONFIG

proxy_l_number=$( grep -n "proxy_pass" $OLDCONFIG | cut -d : -f 1| sed -n '1p')
proxy_line=$(head -n"${proxy_l_number}"  $OLDCONFIG|tail -1 )
location_line_number=$( grep -n "location / {" $OLDCONFIG | cut -d : -f 1 )

newproxy_l_number=$(($location_line_number-1))

# rm $TEMPCONFIG
head -n$newproxy_l_number  $OLDCONFIG >> $TEMPCONFIG
echo "    location = /robots.txt {" >> $TEMPCONFIG
echo "        allow all;" >> $TEMPCONFIG
echo "$proxy_line" >> $TEMPCONFIG
echo "}" >> $TEMPCONFIG
tail  -n +$newproxy_l_number $OLDCONFIG >> $TEMPCONFIG

echo "Changed nginx config of old domain"
echo "Please, check config" 
echo "#################################################################"
cat $TEMPCONFIG
echo "#################################################################"

cp $TEMPCONFIG $CONFIGDIR$domain".nginx.conf"
rm $TEMPCONFIG

echo "" 
echo "Deleted temp config"
echo "" 
nginx -t 2>&1 | grep "is ok" |  awk '{if ($0==0) { print "Nginx not reloaded!!!"} else  {systemctl reload nginx; print "Nginx reloaded!"}}'

echo "" 
echo "Everything is done, master!"
echo "" 
echo "=================================================================~~~~"

chown -R $user:$user $WORKINGDIR

# rm -rf /home/$user/wp

echo "Perekleyka: Done."
exit 0
